apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: http://localhost:9648
      insecure-skip-tls-verify: true
    name: metrics-mock
contexts:
  - context:
      cluster: metrics-mock
      user: metrics-mock-user
    name: metrics-mock
current-context: metrics-mock
users:
  - name: metrics-mock-user
    user: {}
